# Generated by Django 5.1.7 on 2025-03-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_slug_tags_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_uz',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='tags',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='tags',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='tags',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
    ]
